# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daiag < Formula
  desc "CLI tool for orchestrating AI agents through Starlark-defined workflows"
  homepage "https://github.com/nbykovsky/daiag"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.1.0/daiag_darwin_amd64.tar.gz"
      sha256 "76a53f5795e8179cb2200654159ff6c3b518533e30fd03885969dc1be11ee64d"

      define_method(:install) do
        bin.install "daiag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.1.0/daiag_darwin_arm64.tar.gz"
      sha256 "01a5dd7c3ff4872daad89df244741dfd71ca287017d76bab5323ff599c49ab8f"

      define_method(:install) do
        bin.install "daiag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.1.0/daiag_linux_amd64.tar.gz"
      sha256 "3a0c42fd319c85f9a903672d37f267da4c636086cfd1ba147a2aa7cb6a15f87b"
      define_method(:install) do
        bin.install "daiag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.1.0/daiag_linux_arm64.tar.gz"
      sha256 "040aeb69a92defd3cb6d9d3745cf034cb3628b1be9b42e196c80448137f64a8c"
      define_method(:install) do
        bin.install "daiag"
      end
    end
  end

  test do
    system "#{bin}/daiag", "--help"
  end
end
