# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daiag < Formula
  desc "CLI tool for orchestrating AI agents through Starlark-defined workflows"
  homepage "https://github.com/nbykovsky/daiag"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.2.0/daiag_darwin_amd64.tar.gz"
      sha256 "e55644c6c1f46148e4fbbec90b08ee3c916dabeb343f197b29c0e1e72bf46cf6"

      define_method(:install) do
        bin.install "daiag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.2.0/daiag_darwin_arm64.tar.gz"
      sha256 "9332425faa9d454a5c5c475d1cd75ebc5e9af7a6abb67226ecbb8c421513873c"

      define_method(:install) do
        bin.install "daiag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.2.0/daiag_linux_amd64.tar.gz"
      sha256 "d794173d66ed2deff4bc5d67fba863d26a7820efa9fd8b6ba31a26d96f551536"
      define_method(:install) do
        bin.install "daiag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.2.0/daiag_linux_arm64.tar.gz"
      sha256 "814b083cc615da79754c7e38fcdd4f9840838093ac828b42ee965029861a4cde"
      define_method(:install) do
        bin.install "daiag"
      end
    end
  end

  test do
    system "#{bin}/daiag", "--help"
  end
end
