# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Daiag < Formula
  desc "CLI tool for orchestrating AI agents through Starlark-defined workflows"
  homepage "https://github.com/nbykovsky/daiag"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.3.0/daiag_darwin_amd64.tar.gz"
      sha256 "aa0a757f7ca28e3a09a5b0408c4c78db2815e6bcbbafe27b19434a2b1a56ccf3"

      define_method(:install) do
        bin.install "daiag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.3.0/daiag_darwin_arm64.tar.gz"
      sha256 "94db62d81fe4c3a284b34a4e8bb68bd3e99fac420f5d6caa7e39e89e56bfda9c"

      define_method(:install) do
        bin.install "daiag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.3.0/daiag_linux_amd64.tar.gz"
      sha256 "708e52e4cfa5ab65d7304fdf706625938aada0fcc87f0df4b81a1356288d5ed9"
      define_method(:install) do
        bin.install "daiag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nbykovsky/daiag/releases/download/v0.3.0/daiag_linux_arm64.tar.gz"
      sha256 "f87369ac4c2ba4c19abbc056d31dfd6fc377b3c3c4211834e5d92287f84dcee6"
      define_method(:install) do
        bin.install "daiag"
      end
    end
  end

  test do
    system "#{bin}/daiag", "--help"
  end
end
